services:

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: "INFO"
    networks:
      - minima-network

  indexer:
    build: 
      context: ./indexer
      dockerfile: Dockerfile
      args:
        EMBEDDING_MODEL_ID: ${EMBEDDING_MODEL_ID}
        EMBEDDING_SIZE: ${EMBEDDING_SIZE}
    volumes:
      - ${LOCAL_FILES_PATH}:/usr/src/app/local_files/
      - ./indexer:/usr/src/app
      - ./indexer_data:/indexer/storage
      - huggingface_cache:/root/.cache/huggingface
      - nltk_data:/root/nltk_data
    ports:
      - 8001:8000
    environment:
      - PYTHONPATH=/usr/src
      - PYTHONUNBUFFERED=TRUE
      - LOCAL_FILES_PATH=${LOCAL_FILES_PATH}
      - EMBEDDING_MODEL_ID=${EMBEDDING_MODEL_ID}
      - EMBEDDING_SIZE=${EMBEDDING_SIZE}
      - CONTAINER_PATH=/usr/src/app/local_files/
    depends_on:
      - qdrant
    networks:
      - minima-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=3)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  sse-server:
    build: 
      context: ./sse
      dockerfile: Dockerfile
    container_name: minima-sse
    ports:
      - 8003:8003
    environment:
      - INDEXER_URL=http://indexer:8000
      - PYTHONUNBUFFERED=TRUE
    depends_on:
      indexer:
        condition: service_healthy
    networks:
      - minima-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

networks:
  minima-network:
    driver: bridge

volumes:
  huggingface_cache:
    driver: local
  nltk_data:
    driver: local