services:

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: "INFO"
    networks:
      - minima-network

  indexer:
    build: 
      context: ./indexer
      dockerfile: Dockerfile
      args:
        EMBEDDING_MODEL_ID: ${EMBEDDING_MODEL_ID}
        EMBEDDING_SIZE: ${EMBEDDING_SIZE}
    volumes:
      - ${LOCAL_FILES_PATH}:/usr/src/app/local_files/
      - ./indexer:/usr/src/app
      - ./indexer_data:/indexer/storage
      - huggingface_cache:/root/.cache/huggingface
      - nltk_data:/root/nltk_data
    ports:
      - 8002:8002
    environment:
      - PYTHONPATH=/usr/src
      - PYTHONUNBUFFERED=TRUE
      - LOCAL_FILES_PATH=${LOCAL_FILES_PATH}
      - EMBEDDING_MODEL_ID=${EMBEDDING_MODEL_ID}
      - EMBEDDING_SIZE=${EMBEDDING_SIZE}
      - CONTAINER_PATH=/usr/src/app/local_files/
    depends_on:
      - qdrant
    networks:
      - minima-network

  sse-server:
    build: 
      context: ./sse
      dockerfile: Dockerfile
    container_name: minima-sse
    ports:
      - 8003:8003
    environment:
      - INDEXER_URL=http://indexer:8002
      - PYTHONUNBUFFERED=TRUE
    depends_on:
      - indexer
    networks:
      - minima-network

networks:
  minima-network:
    driver: bridge

volumes:
  huggingface_cache:
    driver: local
  nltk_data:
    driver: local